services:
  db:
    environment: {POSTGRES_DB: db, POSTGRES_HOST_AUTH_METHOD: trust}
    image: postgres:9.6-alpine
    volumes: ['.:/app:rw']
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-local
    links: ['db:postgres']
    ports: ['8000:80']
    volumes: ['.:/app:rw']
