version: "3"

services:

  db:
    # the application's web service will use an off-the-shelf image
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
    volumes:
      - ".:/app:rw"

  web:
    # the application's web service (container) will use an image based on our Dockerfile
    build: "."
    # Map the internal port 80 to port 8000 on the host
    ports:
      - "8000:80"
    # Map the host directory to app (which allows us to see and edit files inside the container)
    volumes:
      - ".:/app:rw"
    # The default command to run when launching the container
    command: python manage.py runserver 0.0.0.0:80
    # the URL 'postgres' will point to the application's db service
    links:
      - "db:postgres"
    depends_on:
      - db
    env_file: .env-local
